require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ApatientsController do

  # This should return the minimal set of attributes required to create a valid
  # Apatient. As you add validations to Apatient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApatientsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all apatients as @apatients" do
      apatient = Apatient.create! valid_attributes
      get :index, {}, valid_session
      assigns(:apatients).should eq([apatient])
    end
  end

  describe "GET show" do
    it "assigns the requested apatient as @apatient" do
      apatient = Apatient.create! valid_attributes
      get :show, {:id => apatient.to_param}, valid_session
      assigns(:apatient).should eq(apatient)
    end
  end

  describe "GET new" do
    it "assigns a new apatient as @apatient" do
      get :new, {}, valid_session
      assigns(:apatient).should be_a_new(Apatient)
    end
  end

  describe "GET edit" do
    it "assigns the requested apatient as @apatient" do
      apatient = Apatient.create! valid_attributes
      get :edit, {:id => apatient.to_param}, valid_session
      assigns(:apatient).should eq(apatient)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Apatient" do
        expect {
          post :create, {:apatient => valid_attributes}, valid_session
        }.to change(Apatient, :count).by(1)
      end

      it "assigns a newly created apatient as @apatient" do
        post :create, {:apatient => valid_attributes}, valid_session
        assigns(:apatient).should be_a(Apatient)
        assigns(:apatient).should be_persisted
      end

      it "redirects to the created apatient" do
        post :create, {:apatient => valid_attributes}, valid_session
        response.should redirect_to(Apatient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved apatient as @apatient" do
        # Trigger the behavior that occurs when invalid params are submitted
        Apatient.any_instance.stub(:save).and_return(false)
        post :create, {:apatient => { "first_name" => "invalid value" }}, valid_session
        assigns(:apatient).should be_a_new(Apatient)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Apatient.any_instance.stub(:save).and_return(false)
        post :create, {:apatient => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested apatient" do
        apatient = Apatient.create! valid_attributes
        # Assuming there are no other apatients in the database, this
        # specifies that the Apatient created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Apatient.any_instance.should_receive(:update).with({ "first_name" => "MyString" })
        put :update, {:id => apatient.to_param, :apatient => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested apatient as @apatient" do
        apatient = Apatient.create! valid_attributes
        put :update, {:id => apatient.to_param, :apatient => valid_attributes}, valid_session
        assigns(:apatient).should eq(apatient)
      end

      it "redirects to the apatient" do
        apatient = Apatient.create! valid_attributes
        put :update, {:id => apatient.to_param, :apatient => valid_attributes}, valid_session
        response.should redirect_to(apatient)
      end
    end

    describe "with invalid params" do
      it "assigns the apatient as @apatient" do
        apatient = Apatient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Apatient.any_instance.stub(:save).and_return(false)
        put :update, {:id => apatient.to_param, :apatient => { "first_name" => "invalid value" }}, valid_session
        assigns(:apatient).should eq(apatient)
      end

      it "re-renders the 'edit' template" do
        apatient = Apatient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Apatient.any_instance.stub(:save).and_return(false)
        put :update, {:id => apatient.to_param, :apatient => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested apatient" do
      apatient = Apatient.create! valid_attributes
      expect {
        delete :destroy, {:id => apatient.to_param}, valid_session
      }.to change(Apatient, :count).by(-1)
    end

    it "redirects to the apatients list" do
      apatient = Apatient.create! valid_attributes
      delete :destroy, {:id => apatient.to_param}, valid_session
      response.should redirect_to(apatients_url)
    end
  end

end
